### ISSUE TITLE
How to compile MusOOEvaluator?

### ISSUE THREAD

**Issue by calebkoy** [jpauwels/MusOOEvaluator#2]
Hello, @jpauwels.

I'm building on [the work of Junqi Deng](https://github.com/tangkk/tangkk-mirex-ace), who has created large vocabulary ACE (LVACE) systems using different neural networks. I've created a neural network for LVACE and I want to use MusOOEvaluator to evaluate the predictions of my neural network. 

I've downloaded MusOOEvaluator and installed the boost libraries (version 1.66.0) onto my laptop, but I'm struggling to understand how to compile the software. (Note: I understand the context of ACE and the purpose of MusOOEvaluator. But I'm completely new to C++ and have no experience building and/or compiling software with boost! Also, I'm running Windows 10 and Visual Studio 2017.)

The main issues/questions I have at the moment are as follows:

- In [the MusOOEvaluator README](https://github.com/jpauwels/MusOOEvaluator/blob/master/README.md), what is meant by 'If it has been installed in a non-standard location'? I assume this is referring to MusOOEvaluator, but I'm not sure what a non-standard location is and if I should be concerned with it.
- What is meant by 'the include and library folders containing the boost libraries'?
- Where can I find the variables `COMPILED_LIBRARIES_INCLUDE` and `COMPILED_LIBRARIES_LIB` and what does it mean to set them 'to the include and library folders containing the boost libraries'?

I think I may have more questions about how I actually use the software to carry out an evaluation on my neural network's predictions, but my main goal is to first compile the software!

I look forward to hearing from you as soon as possible. 

Regards, 

Caleb

**Comment by jpauwels** [comment]
The easy answer would be to use the binary [compiled for Windows](https://github.com/jpauwels/MusOOEvaluator/releases). I've made some slight updates since, some of which are in the repo already, so I probably should create an updated release one of these days. In case you want to compile the newer version yourself, here are the answers to your questions.

        In the MusOOEvaluator README, what is meant by 'If it has been installed in a non-standard location'? I assume this is referring to MusOOEvaluator, but I'm not sure what a non-standard location is and if I should be concerned with it.

Sorry for the confusion, the readme is mostly written from a Linux/Mac perspective. I'm referring to the prerequisite libraries being installed in a non-standared location (under Linux, `/usr/local` would be a default location for example). I'm not sure if there are standard locations in Windows too, but I guess not, which means you need to set the environment variables as described below.

        What is meant by 'the include and library folders containing the boost libraries'?

The path to the boost header files (*.h files) and the boost library files (*.lib files) respectively. I guess something like `C:\boost-1.66\include` and `C:\boost-1.66\lib`. This depends on the way you installed boost and there should be some info in the boost manual. If you can't figure this out, send me a screenshot of your boost folder.

        Where can I find the variables COMPILED_LIBRARIES_INCLUDE and COMPILED_LIBRARIES_LIB and what does it mean to set them 'to the include and library folders containing the boost libraries'?

They don't exist yet :-) They're environment variables and you need to create them yourself ([tutorial](https://www.youtube.com/watch?v=bEroNNzqlF4)). Following the example above, you set `COMPILED_LIBRARIES_INCLUDE` to `C:\boost-1.66\include` and `COMPILED_LIBRARIES_LIB` to `C:\boost-1.66\lib`. Alternatively, you can directly modify the Visual Studio project file and replace the variables with the pathnames in the project file.

**Comment by calebkoy** [comment]
Thank you for the quick and detailed response, @jpauwels! I'll start with the binary compiled with Windows, see how I get on with that and, if it's all fine, I'll close this issue. :)

**Comment by calebkoy** [comment]
I've downloaded the binary compiled for Windows and have run it from the Developer Command Prompt for VS 2017. I get the following output:

![image](https://user-images.githubusercontent.com/13520810/36445416-21032c48-1676-11e8-9767-1354a1c13243.png)

Am I right in assuming that everything is set up for me to start using MusOOEvaluator (and that I now just need my neural network predictions [yet to be generated] and ground truth to actually compute scores)?

**Comment by calebkoy** [comment]
I've managed to solve the issue. I used my neural network to predict chord labels for a single song and then ran `MusOOEvaluator.exe --reffile C:\Users\caleb\Desktop\University\CS344\anjing.txt --testfile C:\Users\caleb\Desktop\University\CS344\anjing_predictions.txt --chords MirexSeventhsBass --output C:\Users\caleb\Desktop\University\CS344\output_anjing_WCSR.txt`, which outputted the evaluation. It's working!
