### ISSUE TITLE
Are my WCSR scores biased when assuming that estimated start and end times are the same as the ground truth?

### ISSUE THREAD

**Issue by calebkoy** [jpauwels/MusOOEvaluator#6]
Hi, @jpauwels. This is to ask for clarification about the way evaluation works when assuming that the estimated start and end times are the same as the ground truth (gt) start and end times.

I'd like to compare my WCSR scores to [Junqi Deng's](https://github.com/tangkk/phd-thesis-junqi-deng/blob/master/junqi-thesis-hku.pdf). (In his experiments, he _predicts_ start and end times and doesn't make the assumption that I'm making). 

WCSR is defined as follows:
![tmp_wcsr](https://user-images.githubusercontent.com/13520810/37247265-8774ca20-24b0-11e8-8dba-6162b94a023c.PNG), 
where CSR is defined as follows: 
![tmp_csr](https://user-images.githubusercontent.com/13520810/37247269-9c40899e-24b0-11e8-85a8-bc93f1a5442e.PNG). 
In his [thesis](https://github.com/tangkk/phd-thesis-junqi-deng/blob/master/junqi-thesis-hku.pdf), Junqi gives a verbal definition of CSR as: 
![tmp_csr_in_words](https://user-images.githubusercontent.com/13520810/37247273-b04841ca-24b0-11e8-9d41-2978683bca5f.PNG)

Let's assume that we're dealing with a single song. Then my understanding of these definitions is that the intersection of S and S* contains all segments (corresponding lines in the reference and test files) for which:

1. There's overlap between the gt start-end window and the estimated start-end window, AND
2. The gt and estimated chord annotations are equal.

**_Is the above correct?_** Also, point 1 above suggests that, if the estimated start-end window for a segment has no overlap with the corresponding gt start-end window, then (even if the chord annotations are equal) this segment contributes nothing to the CSR score. _**Is this correct?**_

Finally, my understanding is that the phrase 'total duration' mentioned in the verbal definition of CSR refers to the total duration of the gt segment (in both the numerator and denominator of CSR), not the total duration of the estimated segment. _**Is this correct?**_ 

If my understanding so far is correct, then I think that, by using the gt start-end times as the start-end times for my test files, I'm giving myself a higher chance of getting a good WCSR score (because the segments in my test files have greater chance of overlapping with the gt segments), **_right?_**. And so, to compare my WCSR scores with Junqi's, I shouldn't be assuming that estimated start-end times are the same as gt start-end times (but instead my test files should perhaps use the start-end windows that Junqi predicts in his experiments). (Note that I'm using exactly the same data and gt files he uses. The only difference is that I'm not predicting start-end times; I could use his code to produce the predicted start-end times he used, if necessary). 

Thank you in advance!

**Comment by jpauwels** [comment]
Hi Caleb, all looks correct. Some further clarifications:

    Then my understanding of these definitions is that the intersection of S and S* contains all segments (corresponding lines in the reference and test files) for which:

    1. There's overlap between the gt start-end window and the estimated start-end window, AND
    2. The gt and estimated chord annotations are equal.

    Is the above correct?
Yes

    Also, point 1 above suggests that, if the estimated start-end window for a segment has no overlap with the corresponding gt start-end window, then (even if the chord annotations are equal) this segment contributes nothing to the CSR score. Is this correct?
Yes, although I wouldn't say that window contributes "nothing", rather it contributes a score of zero, cause an evaluation is still taking place (small difference, I know). It doesn't contribute to the denominator, so in that sense your sentence is correct. Also, `even if the chord annotations are equal` is not really relevant cause the both chord labels describe different points in time, so can't be compared. If your estimation is identical to the ground truth, but shifted 10 seconds (for example) the score will be very low.

    Finally, my understanding is that the phrase 'total duration' mentioned in the verbal definition of CSR refers to the total duration of the gt segment (in both the numerator and denominator of CSR), not the total duration of the estimated segment. Is this correct?

Yes, annotated segments = ground truth. In more advanced scenarios you could exclude some annotated labels from the evaluation (if you only want to evaluate performance on four-note chords for instance), but the total duration is always determined by the reference/ground-truth, otherwise the estimated output would influence the evaluation procedure (see also ICASSP paper).

    If my understanding so far is correct, then I think that, by using the gt start-end times as the start-end times for my test files, I'm giving myself a higher chance of getting a good WCSR score (because the segments in my test files have greater chance of overlapping with the gt segments), right?.
Absolutely

     And so, to compare my WCSR scores with Junqi's, I shouldn't be assuming that estimated start-end times are the same as gt start-end times (but instead my test files should perhaps use the start-end windows that Junqi predicts in his experiments). (Note that I'm using exactly the same data and gt files he uses. The only difference is that I'm not predicting start-end times; I could use his code to produce the predicted start-end times he used, if necessary).
The points you make are not specifically tied to a specific form of evaluation, but again are more about experiment design. A realistic chord estimation scenario requires both chord segmentation and identification of those segments (as separate steps or integrated into one). Since you provide a segmentation, you are only doing the identification, so it's not fair to compare your results to Junqi's. If you cut your audio according to the start-end times the comparison will be fairer, where you could argue that you're constructing a two stage system with Junqi's algorithm doing the segmentation and your part doing the identification.

You can also try to find out what the upper limit is for the score given Junqi's segmentation by mapping the ground truth segments onto Junqi's segments (by simply assigning the value of the gt segment with largest overlap to each test segment) and evaluating the result. (Hope this makes sense).

**Comment by calebkoy** [comment]
Hi, Johan. 

Thanks for the clarification! This is very helpful. I've spent the past week trying (and managing) to use Junqi's system to segment my predictions. So now I'll be able to compare mine with his. Regardless, this is a helpful response and, yes, it makes sense!
